# Cargo.toml

[package]
name = "mvframe"
version.workspace = true
edition.workspace = true

[dependencies]
# async runtime
tokio.workspace = true

# backend imgui
imgui.workspace = true

# backend winit
winit.workspace = true
imgui-winit-support = "0.13.0"

# backend opengl
glutin = "0.32.3"
glutin-winit = "0.5.0"
imgui-glow-renderer = "0.13.0"

# libs
mvcore.workspace = true
mvplugin.workspace = true
